$(document) . ready (function () {
    let element = $(".content")
    let text = element . html ()
                       . replaceAll ("%%WHITE%%", "&#x25CB;")
                       . replaceAll ("%%BLACK%%", "&#x25CF;")
                       . replace ('"', '"' + "<span class = 'subject'>")
                       . replace (';"', ';</span>"')
                       . replace ('/\\', '/<span class = "pattern">\\')
                       . replace (';/', ";</span>/")
    element . html (text)
})
